export const LOGIN_METHOD = {
  TWO_FA: 2,
};

export const AUTH_MESSAGE_KEYS = {
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const PROFILE_KEYS = {
  CHANGE_PROCESS_SUCCESS: "CHANGE_PROCESS_SUCCESS",
};
